### ISSUE TITLE
字体问题

### ISSUE THREAD

**Issue by fengz63** [NWPUMetaphysicsOffice/LaTeX-Template-For-NPU-Thesis#16]
你好，那个西工大的艺术字体一直提示找不到该怎么解决。

**Comment by polossk** [comment]
您好！
下载整个版本之后，打开 `setting` 文件夹，双击 `nwpuname.ttf` 字体文件，点击安装即可。

**Comment by fengz63** [comment]
> 您好！
> 下载整个版本之后，打开 `setting` 文件夹，双击 `nwpuname.ttf` 字体文件，点击安装即可。

谢谢了，之前一直有问题，刚才突然就能用了

**Comment by polossk** [comment]
OK 随时欢迎提问
