### ISSUE TITLE
参考文献格式问题

### ISSUE THREAD

**Issue by striderdu** [NWPUMetaphysicsOffice/LaTeX-Template-For-NPU-Thesis#18]
你好，官方word模板提供的参考文献格式如下：
> 文献作者3名以内全部列出，4名以上只列出前3名，后加“，等”；
外文作者姓在前，首字为大写，名缩写为首字母，与姓之间空一字符，不加缩写点。

现在的问题是，在4名以上作者的情况时，生成的参考文献只有一个作者，想请教一下控制参考文献格式的文件是哪个，能否提供修改建议？

**Comment by polossk** [comment]
我已经定位问题所在，请等待更新。

**Comment by polossk** [comment]
问题已经解决。例如如下所示的 bibtex item

```bibtex
@article{szegedy2015going,
	title={Going deeper with convolutions},
	author={Szegedy, Christian and Liu, Wei and Jia, Yangqing and Sermanet, Pierre and Reed, Scott E and Anguelov, Dragomir and Erhan, Dumitru and Vanhoucke, Vincent and Rabinovich, Andrew},
	journal={computer vision and pattern recognition},
	pages={1--9},
	year={2015}
}
```
引用之后会生成这样的参考文献
```plain
Szegedy C, Liu W, Jia Y, et al. Going deeper with convolutions[J]. computer vision and pattern recognition, 2015:1-9.
```

即完整的遵守了 GBT7714 2015 版的规定。

**Comment by polossk** [comment]
代码已经合并至 master
请更新 nputhesis.bst 文件
相关pr #19

**Comment by polossk** [comment]
如果仍有其他问题请及时指出

**Comment by striderdu** [comment]
还想咨询一下关于列表环境的缩进的问题：
能否将列表环境的label与item的缩进设置成与段落缩进相同？

**Comment by polossk** [comment]
具体格式定制问题请参阅所用包的相关文档，本模板并未提供定制服务。

**Comment by polossk** [comment]
我不知道你手头有没有任何关于 LaTeX 的辅导书。如果没有的话推荐去图书馆借阅一本《LaTeX 入门》（刘海洋 著），该书的 p102 页，2.2.3.3 定制列表环境中，有非常详细的讲解。该节中也讲解了间隔控制所用到的各种长度参数（详见书中 p104 页图 2.3）。应该能解决你的问题。

**Comment by polossk** [comment]
如有任何与该 issue 主题相关的内容，请直接在这里回复；否则请另开新的 issue。
