### ISSUE TITLE
希望加入对插入空白页的支持

### ISSUE THREAD

**Issue by striderdu** [NWPUMetaphysicsOffice/LaTeX-Template-For-NPU-Thesis#20]
空白页带页眉 页码与所在环境相同 例如 中文摘要的背面空白页为ii页 第47页的背面空白页为48页

**Comment by polossk** [comment]
tex 支持很多种空白页，如 `\clearpage`，`\cleardoublepage`，甚至你可以写一个空盒子强制塞满一页。

这些是 tex 的基本操作，与模板毫无关系。

推荐您找本书仔细看，用心学哦。
